env_name: evo_bipedalwalker_easy
agent_spec:
  batch_design: False
# training parameters
gamma: 0.99
tau: 0.95

policy_spec:
  scale_htype: tanh
  scale_mlp: [64, 64]
  scale_log_std: 0
  scale_fix_control_std: False
  control_htype: tanh
  control_mlp: [64, 128, 64]
  control_log_std: 0
  control_fix_control_std: False

policy_optimizer: 'Adam'
policy_lr: 5.e-5
policy_momentum: 0.0
policy_weight_decay: 0.0

value_spec:
  htype: tanh
  mlp: [64, 64, 64]

value_optimizer: 'Adam'
value_lr: 3.e-4
value_momentum: 0.0
value_weight_decay: 0.0

l2_reg: 1e-3
clip_epsilon: 0.2
entropy_coeff: 1.e-4
batch_size: 8000
eval_batch_size: 2000
mini_batch_size: 64
optim_num_epoch: 10
max_iter_num: 1000
seed: 1
save_model_interval: 50

use_post_reward: True
use_entire_obs: True